apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: the-notebook-app

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: the-notebook-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceAccount.yaml
  - rbac.yaml
