apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: the-notebook-app
  namespace: the-notebook-app
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: the-notebook-app
  namespace: the-notebook-app
subjects:
  - kind: ServiceAccount
    name: the-notebook-app
    namespace: the-notebook-app
roleRef:
  kind: Role
  name: the-notebook-app
  apiGroup: rbac.authorization.k8s.io
