apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-notebook-app
spec:
  template:
    spec:
      containers:
        - name: the-notebook-app
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              port: 5000
